# Generated by Django 4.2.7 on 2025-10-09 12:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audio_file', models.CharField(help_text='Path to audio file', max_length=500)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('file_format', models.CharField(max_length=10)),
                ('transcribed_text', models.TextField(blank=True, null=True)),
                ('intent', models.CharField(blank=True, help_text='AI-generated intent category', max_length=200, null=True)),
                ('intent_confidence', models.FloatField(blank=True, null=True)),
                ('intent_summary', models.TextField(blank=True, help_text='Brief summary of request', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'voice_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='voice_reque_status_d7b1f1_idx'), models.Index(fields=['intent'], name='voice_reque_intent_9212c7_idx')],
            },
        ),
    ]
