# Generated by Django 4.2.7 on 2025-10-15 12:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicerequest',
            name='action_items',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, help_text='Action items or tasks mentioned', size=None),
        ),
        migrations.AddField(
            model_name='voicerequest',
            name='domain_terms',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text='Domain-specific technical terms', size=None),
        ),
        migrations.AddField(
            model_name='voicerequest',
            name='entities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text='Named entities (people, places, organizations)', size=None),
        ),
        migrations.AddField(
            model_name='voicerequest',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='Important keywords extracted from transcription', size=None),
        ),
        migrations.AddField(
            model_name='voicerequest',
            name='topics',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text='Main topics/themes discussed', size=None),
        ),
        migrations.AddIndex(
            model_name='voicerequest',
            index=models.Index(fields=['keywords'], name='voice_reque_keyword_fa2b0f_idx'),
        ),
    ]
