# Generated by Django 4.2.7 on 2025-10-17 15:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('voice_api', '0002_voicerequest_action_items_voicerequest_domain_terms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(help_text="User's phone number", max_length=20, unique=True)),
                ('total_messages', models.IntegerField(default=0)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'chat_conversations',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='PhoneVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(help_text='International phone number with country code', max_length=20)),
                ('otp_code', models.CharField(help_text='6-digit OTP code', max_length=6)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_attempts', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(help_text='OTP expiration time')),
            ],
            options={
                'db_table': 'phone_verifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number', 'is_verified'], name='phone_verif_phone_n_baa12f_idx'), models.Index(fields=['otp_code'], name='phone_verif_otp_cod_7831b3_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('user', 'User'), ('bot', 'Bot')], max_length=10)),
                ('audio_file', models.CharField(blank=True, help_text='Path to audio file', max_length=500, null=True)),
                ('transcribed_text', models.TextField(blank=True, null=True)),
                ('response_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='voice_api.chatconversation')),
            ],
            options={
                'db_table': 'chat_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['phone_number'], name='chat_conver_phone_n_f98696_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='chat_messag_convers_0a903c_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['message_type'], name='chat_messag_message_b8fb34_idx'),
        ),
    ]
