# Generated by Django 4.2.7 on 2025-10-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_api', '0003_chatconversation_phoneverification_chatmessage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatconversation',
            name='phone_number',
            field=models.CharField(db_column='phone_number', help_text="User's email address", max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='phoneverification',
            name='phone_number',
            field=models.CharField(db_column='phone_number', help_text='Email address for verification', max_length=255),
        ),
    ]
