# Generated by Django 4.2.7 on 2025-10-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_api', '0004_update_email_based_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatconversation',
            name='title',
            field=models.CharField(default='New Chat', help_text='Auto-generated conversation title', max_length=255),
        ),
        migrations.AlterField(
            model_name='chatconversation',
            name='phone_number',
            field=models.CharField(db_column='phone_number', help_text="User's email address", max_length=255),
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['phone_number', '-last_activity'], name='chat_conver_phone_n_2b1101_idx'),
        ),
    ]
