# Generated by Django 4.2.7 on 2025-10-21 16:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('voice_api', '0005_chatconversation_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatconversation',
            name='conversation_summary',
            field=models.TextField(blank=True, help_text='AI-generated summary of the conversation', null=True),
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='summary_generated_at',
            field=models.DateTimeField(blank=True, help_text='When the summary was last updated', null=True),
        ),
        migrations.CreateModel(
            name='ContextQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField(help_text="User's question about the context")),
                ('answer', models.TextField(help_text='AI-generated answer')),
                ('context_summary', models.TextField(blank=True, help_text='Summary of context when question was asked', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context_questions', to='voice_api.chatconversation')),
                ('message', models.ForeignKey(help_text='The message this question is about', on_delete=django.db.models.deletion.CASCADE, related_name='context_questions', to='voice_api.chatmessage')),
            ],
            options={
                'db_table': 'context_questions',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['conversation', 'created_at'], name='context_que_convers_aa3506_idx'), models.Index(fields=['message'], name='context_que_message_bcee30_idx')],
            },
        ),
    ]
