# Generated by Django 4.2.7 on 2025-10-22 06:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_api', '0007_calendarappointment_appointmentrecording'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='action_items',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, help_text='Action items and tasks identified', size=None),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='domain_terms',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text='Technical or domain-specific terms', size=None),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='entities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text='Named entities mentioned', size=None),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='intent',
            field=models.CharField(blank=True, help_text='Message intent', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='Important keywords from the message', size=None),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='topics',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text='Topics discussed in the message', size=None),
        ),
    ]
