# Generated by Django 4.2.7 on 2025-10-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_api', '0008_chatmessage_action_items_chatmessage_domain_terms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='attachment_file',
            field=models.CharField(blank=True, help_text='Path to attachment file', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='attachment_name',
            field=models.CharField(blank=True, help_text='Original filename', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='attachment_size',
            field=models.IntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='attachment_type',
            field=models.CharField(blank=True, choices=[('image', 'Image'), ('pdf', 'PDF Document'), ('document', 'Document'), ('other', 'Other')], help_text='Type of attachment', max_length=50, null=True),
        ),
    ]
