# Generated by Django 4.2.7 on 2025-10-22 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voice_api', '0009_chatmessage_attachment_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarappointment',
            name='meeting_url',
        ),
    ]
