# Generated by Django 4.2.7 on 2025-10-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_api', '0010_remove_calendarappointment_meeting_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarappointment',
            name='conversation_id',
            field=models.UUIDField(blank=True, help_text='Linked chat conversation ID', null=True),
        ),
        migrations.AddField(
            model_name='calendarappointment',
            name='conversation_link_sent',
            field=models.BooleanField(default=False, help_text='Whether conversation link email was sent'),
        ),
    ]
