# Generated by Django 4.2.7 on 2025-10-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_api', '0011_add_conversation_link_to_appointments'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarappointment',
            name='base_url',
            field=models.CharField(blank=True, help_text='Base URL for generating email links', max_length=255, null=True),
        ),
    ]
